# .github/workflows/publish-docs.yml
name: Build and Push Typedoc

on:
  push:
    branches:
      - main
      - beta

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the package repo
      - name: Checkout package
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Typedoc using typedoc.json
      - name: Generate Typedoc
        run: npx typedoc

      # Get package name from package.json
      - name: Get package name
        id: pkg
        run: |
          echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV

      # Checkout central docs repo (main branch) into a separate folder
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: xernerx/docs
          token: ${{ secrets.XERNERX_ACCESS_TOKEN }}
          ref: main
          path: central-docs   # <-- separate folder for central repo

      # Copy Typedoc output from package repo into central docs repo
      - name: Sync docs
        run: |
          rm -rf central-docs/docs/${PACKAGE_NAME}
          mkdir -p central-docs/docs/${PACKAGE_NAME}
          cp -r ./docs/* central-docs/docs/${PACKAGE_NAME}/

      # Commit & push changes
      - name: Commit and push
        run: |
          cd central-docs
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update ${PACKAGE_NAME} docs from $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
